# Generated by Django 5.2.8 on 2025-11-16 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ashenone_app", "0002_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("game_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LORE", "Lore Summary"),
                            ("BOSS", "Boss Guide"),
                            ("BUILD", "Build Guide"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content_body", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["game_name", "title"],
            },
        ),
    ]
