# Generated by Django 5.2.6 on 2025-12-06 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashenone_app', '0003_guidecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidecontent',
            name='game_name',
            field=models.CharField(choices=[('Dark Souls I', 'Dark Souls I'), ('Dark Souls II', 'Dark Souls II'), ('Dark Souls III', 'Dark Souls III'), ('Bloodborne', 'Bloodborne'), ('Sekiro', 'Sekiro'), ('Demon Souls', 'Demon Souls'), ('Elden Ring', 'Elden Ring'), ('Elden Ring: Nightreign', 'Elden Ring: Nightreign')], max_length=100),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('TOXIC', 'ใช้ถ้อยคำหยาบคาย / Toxic'), ('SPAM', 'สแปมข้อความ / โฆษณา'), ('SCAM', 'หลอกลวง / โกง'), ('OTHER', 'อื่นๆ')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติม หรือหลักฐาน')),
                ('status', models.CharField(choices=[('PENDING', 'รอการตรวจสอบ'), ('RESOLVED', 'จัดการแล้ว'), ('DISMISSED', 'ยกเลิก / ไม่มีความผิด')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
